# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: |
    (?x)^(
        # These files are vendored from elsewhere, don't process them
        LICENSE|
        docs/hunspell/.*|
        src/ed25519/.*|
        include/libtorrent/aux_/route\.h|
        test/.*\.xml|
        test/ssl/.*\.pem
    )$
default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    #-   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-xml
    -   id: debug-statements
    -   id: check-symlinks
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.7.0
  hooks:
  - id: rst-directive-colons
  - id: rst-inline-touching-normal
- repo: https://gitlab.com/pycqa/flake8.git
  rev: 3.8.4
  hooks:
  - id: flake8
    exclude: |
        (?x)^(
            # Enable these later, avoid bloating this PR
            bindings/c/tools/gen_alert_header.py|
            bindings/c/tools/gen_header.py|
            fuzzers/tools/generate_initial_corpus.py|
            test/websocket_server.py|
            tools/benchmark_checking.py
        )$
